# fly.toml app configuration file generated for kraken-stremio on 2026-05-22T20:26:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kraken-stremio'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PALANTIR_MORIA_DB = '/data/moria.db'
  PALANTIR_MORIA_ZM3 = '/app/moria_3_3_9.zm3'
  PALANTIR_MORIA_ZM3_URL = 'https://github.com/Hostberry-project/kraken/raw/refs/heads/main/moria_3_3_9.zm3'
  PORT = '8080'
  PUBLIC_URL = 'https://kraken-9tyojw.fly.dev'

[[mounts]]
  source = 'moria_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '1m0s'
    method = 'GET'
    path = '/health.json'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
